services:
  letter-maker:
    build: .
    expose:
      - 3000
    env_file:
      - .env  # Load environment variables from file
    environment:
      # These override any values from env_file
      VIRTUAL_PORT: 3000 # tells nginx proxy what port the app is listening on
      VIRTUAL_HOST: lettermaker.tk.sg # domain for the app
      NODE_ENV: production
      LETSENCRYPT_HOST: lettermaker.tk.sg # for SSL certificate
      LETSENCRYPT_EMAIL: yjsoon@tinkertanker.com # for SSL notifications
    volumes:
      # Persist data if needed
      - ./data/tmp:/app/tmp
    networks:
      devtksg: # same network that the reverse proxy is on
    restart: always

networks:
  devtksg:
    external: true